"""Generate all dialogue with Kokoro, pitch-shift characters, and write timeline data.

Outputs:
  audio/dialogue/<id>.wav            dry 48k mono line
  audio/timeline.json                line timings (global seconds) + text
  kits/lipsync.js                    A.LIPSYNC[who] = per-frame mouth openness (0..1) at 30fps over 60s,
                                     A.LINES = timings for subtitles / scene logic
"""
import json, os, sys
import numpy as np, soundfile as sf
from scipy.signal import resample_poly
from kokoro_onnx import Kokoro

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FPS, SR = 30, 48000
_S = json.load(open(f"{ROOT}/audio/script.json")); script = _S["lines"]; DUR = _S.get("duration", 60.0)
k = Kokoro("/opt/kokoro/kokoro-v1.0.onnx", "/opt/kokoro/voices-v1.0.bin")
os.makedirs(f"{ROOT}/audio/dialogue", exist_ok=True)


def trim(x, thr=0.01):
    idx = np.where(np.abs(x) > thr)[0]
    if not len(idx):
        return x
    return x[max(0, idx[0] - 240): idx[-1] + 2400]


timeline, nframes = [], int(FPS * DUR)
mouths = {}
for L in script:
    ratio = 2 ** (L["pitch"] / 12)
    # pre-slow by ratio so that playing faster (pitch up) restores the intended pace
    s, sr = k.create(L.get("say", L["text"]), voice=L["voice"], speed=L["speed"] / ratio, lang="en-us")
    s = trim(np.asarray(s, dtype=np.float64))
    # resample to 48k while pitch shifting: output rate SR, pretend input rate sr*ratio
    from fractions import Fraction
    fr = Fraction(SR / (sr * ratio)).limit_denominator(2000)
    y = resample_poly(s, fr.numerator, fr.denominator)
    y = y / (np.max(np.abs(y)) + 1e-9) * 0.89
    sf.write(f"{ROOT}/audio/dialogue/{L['id']}.wav", y.astype(np.float32), SR)
    d = len(y) / SR
    # words with approximate timings (proportional to syllable-ish char counts)
    words = L["text"].split()
    wts = np.array([max(2, len(w.strip(".,!?"))) + 1.5 for w in words], float)
    starts = np.concatenate([[0], np.cumsum(wts)[:-1]]) / wts.sum() * d
    timeline.append({**L, "dur": round(d, 3), "end": round(L["t"] + d, 3),
                     "words": [{"w": w, "t": round(L["t"] + st, 3)} for w, st in zip(words, starts)]})
    # mouth envelope
    env = mouths.setdefault(L["who"], np.zeros(nframes))
    hop = SR // FPS
    for i in range(int(np.ceil(len(y) / hop))):
        f = int(round(L["t"] * FPS)) + i
        if 0 <= f < nframes:
            seg = y[i * hop:(i + 1) * hop]
            env[f] = max(env[f], np.sqrt(np.mean(seg ** 2)) if len(seg) else 0)
    print(f"{L['id']:6s} {L['who']:9s} {L['t']:5.1f}-{L['t']+d:5.2f}  {L['text']}")

# overlap check per speaker and overall
tl = sorted(timeline, key=lambda x: x["t"])
for a, b in zip(tl, tl[1:]):
    if a["end"] > b["t"] - 0.1:
        print(f"!! OVERLAP {a['id']} ends {a['end']} > {b['id']} starts {b['t']}", file=sys.stderr)

lips = {}
for who, env in mouths.items():
    e = env / (np.percentile(env[env > 0], 95) + 1e-9)
    e = np.clip(e, 0, 1)
    e = np.convolve(e, [0.25, 0.5, 0.25], mode="same")  # soften
    lips[who] = [round(float(v), 2) for v in e]

json.dump({"fps": FPS, "duration": DUR, "lines": timeline}, open(f"{ROOT}/audio/timeline.json", "w"), indent=1, ensure_ascii=False)
with open(f"{ROOT}/kits/lipsync.js", "w") as f:
    f.write("// AUTO-GENERATED by tools/tts.py — do not edit\n")
    f.write("A.LIPSYNC = " + json.dumps(lips) + ";\n")
    f.write("A.LINES = " + json.dumps([{k2: L[k2] for k2 in ("id", "who", "t", "end", "text", "he", "words")} for L in timeline], ensure_ascii=False) + ";\n")
print("ok")
